</head>
<body>
<section>
    <div class="bg"></div>
    <div class="overlay"></div>
    <div class="overlay-superior"></div>
    <div class="center">
        <div class="box-cadastro-usuario box-formulario fadeIn">
            <a class="close fadeIn" href="<?php echo BASE ?>index/"><i class="fa fa-times-circle" aria-hidden="true"></i></a>
            <?php echo (isset($this->alert) ? $this->alert : ''); ?>
            <form action="<?php echo BASE; ?>cadastro/cadastrar" method="post" class="formulario">
                <h2>Cadastre-se</h2>
                <input type="text" name="nome" required="" placeholder="Nome">
                <input type="text" name="curso" required="" placeholder="Curso">
                <input type="text" name="instituicao" required="" placeholder="Instituição">
                <input type="email" name="email" required="" placeholder="Email">
                <input type="password" name="password" required="" placeholder="Senha">

                <input type="submit" value="Cadastrar">
            </form>
        </div>

        <div id="recuperar-usuario" class="modal">
            <form method="post" class="formulario">
                <h2>Recuperar senha</h2>
                <input type="email" name="email-recuperar-senha" required="" placeholder="Email">
                <input type="submit" value="Enviar" name="recuperar-usuario" rel="modal:close">
            </form>
        </div>

    </div>
</section>
