</head>
</body>

<header>
    <div>
      <h3>NOME DO SISTEMA </h3>
    </div>
</header>
<nav class="nav left">
  <div class="div-nav">
    <ul>
      <a href="<?php echo BASE; ?>" title="Home">
        <li><i class="fa fa-home" aria-hidden="true"></i></li>
      </a>
      <a href="<?php echo BASE; ?>evento" title="Criar Evento">
        <li class="active"><i class="fa fa-plus" aria-hidden="true"></i></li>
      </a>
      <a href="<?php echo BASE . 'login/sair'; ?>" title="Sair">
        <li><i class="fa fa-sign-out" aria-hidden="true"></i></li>
      </a>
    </ul>
  </div>
</nav>

<section class="evento">
  <div class="center">
    <form method="post" action="<?php echo BASE . 'evento/criar'; ?>" id="form" class="formulario">
      <div class="left w40 forms">
        <h4>Crie seu evento<h4>
        <input type="text" required id="titulo" name="titulo" placeholder="Titulo"/>
        <select id="tema" name="tema">
          <option value="Construção Civil">Construção Civil</option>
          <option value="Informática">Informática</option>
          <option value="Automação">Automação</option>
          <option value="Linguagens">Linguagens</option>
          <option value="Humanidades">Humanidades</option>
          <option value="Diversos">Diversos</option>
        </select>
        <div class="sub-div-form left">
          <input type="date" required id="dataI" name="dataI"/>
        </div>
        <div class="sub-div-form rigth">
            <input type="date" id="dataF" name="dataF"/>
        </div>
        <div class="clear"></div>
        <input id="pac-input" name="local" type="text" placeholder="Local" required>
        <?php echo (isset($this->alert) ? $this->alert : '' ) ?>
        <input type="submit" value="Criar"/>
      </div>

      <div class="rigth w60 mapa">
        <div id="map"></div>
        <input type="hidden" readonly id="lat" name="lat"/>
        <input type="hidden" readonly id="long" name="lng"/>
      </div>
      <div class="clear"></div>
    </form>
  </div>
</section>
<footer>
  <p>Amanda e Rafaela</p>
</footer>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZvuc7iH540mu6qnVyXhi29X24yrD0RlY&libraries=places&callback=initAutocomplete"
         async defer></script>

<script src="<?php echo JS; ?>mapa.js"></script>
