</head>
</body>

<header>
    <div class="header">
      <div class="center">
        <h4 class="left">NOME DO SISTEMA </h4>
        <a class="rigth" href="<?php echo BASE . 'login/sair'; ?>">sair</a>
        <div class="clear"></div>
      </div>
    </div>
    <div class="sub-header">
      <div class="center">
        <h2>Criar evento</h2>
      </div>
    </div>
  </header>
  <section class="section-evento">
      <div class="center">
        <form method="post" action="<?php echo BASE . 'evento/criar'; ?>" id="form" class="formulario">
          <div class="left w40">
            <h4>Titulo</h4>
            <input type="text" required id="titulo" name="titulo"/>
            <div class="sub-div-form left">
              <h4>Periodo</h4>
              <input type="date" required id="periodo" name="periodo"/>
            </div>
            <div class="sub-div-form rigth">
              <h4>Tema</h4>
              <select id="tema" name="tema">
                <option value="Contrução Civil">Contrução Civil</option>
                <option value="Informática">Informática</option>
                <option value="Automação">Automação</option>
                <option value="Linguagens">Linguagens</option>
                <option value="Humanidades">Humanidades</option>
                <option value="Diversos">Diversos</option>
              </select>
            </div>
            <div class="clear"></div>
          </div>
          <div class="rigth w60 mapa">
            <input id="pac-input" type="text" placeholder="Buscar...">
            <div id="map"></div>
            <input type="text" readonly id="lat" name="lat"/>
            <input type="text" readonly id="long" name="lng"/>
          </div>
          <div class="clear"></div>
          <input type="submit" value="criar"/>
        </form>
      </div>
  </section>
  <script>
  function initMap() {
    var map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -6.889582, lng: -38.544935},
      zoom: 18
    });
    var infoWindow = new google.maps.InfoWindow({map: map});

    // Try HTML5 geolocation.
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var pos = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };

        infoWindow.setPosition(pos);
        infoWindow.setContent('Location found.');
        map.setCenter(pos);
      }, function() {
        handleLocationError(true, infoWindow, map.getCenter());
      });
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
  }

  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    infoWindow.setPosition(pos);
    infoWindow.setContent(browserHasGeolocation ?
                          'Error: The Geolocation service failed.' :
                          'Error: Your browser doesn\'t support geolocation.');
  }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvUhehS52WPxo9Auyw_7dO7HHyLlqzmcU&libraries=places&callback=initAutocomplete"
         async defer></script>

<script src="<?php echo JS; ?>mapa.js"></script>
