<section>
    <div class="bg"></div>
    <div class="overlay"></div>
    <div class="center">
        <div class="box-login">
            <?php echo (isset($this->alert) ? $this->alert : '' ) ?>
            <form method="post" action="index/logar" class="formulario">
                <h4>Email</h2>
                <input type="email" name="email" required="">
                <h4>Senha</h2>
                <input type="password" name="password" required="">
                <input type="submit" value="Login" name="logar">
            </form>
            <p class="left"><a href="#cadastro-usuario" rel="modal:open" >Registre-se</a></p>
            <p class="rigth"><a href="#recuperar-usuario" rel="modal:open">Esqueceu a senha?</a></p>
            <div class="clear"></div>
        </div>

        <div id="cadastro-usuario" class="modal">
            <form action="<?php echo BASE; ?>index/cadastrar" method="post" class="formulario">
                <h2>Cadastre-se</h2>
                <input type="text" name="nome" required="" placeholder="Nome">
                <input type="text" name="curso" required="" placeholder="Curso">
                <input type="text" name="instituicao" required="" placeholder="Instituição">
                <input type="email" name="email" required="" placeholder="Email">
                <input type="password" name="password" required="" placeholder="Senha">

                <input type="submit" value="Cadastrar">
            </form>
        </div>

        <div id="recuperar-usuario" class="modal">
            <form method="post" class="formulario">
                <h2>Recuperar senha</h2>
                <input type="email" name="email-recuperar-senha" required="" placeholder="Email">
                <input type="submit" value="Enviar" name="recuperar-usuario" rel="modal:close">
            </form>
        </div>

    </div>
</section>
