</head>
<body>
<section>
    <div class="bg"></div>
    <div class="overlay"></div>
    <div class="center">
        <div class="box-login box-formulario fadeIn">
            <?php echo (isset($this->alert) ? $this->alert : '' ) ?>
            <form method="post" action="index/logar" class="formulario">
                <h4>Email</h2>
                <input type="email" name="email" required="">
                <h4>Senha</h2>
                <input type="password" name="password" required="">
                <input type="submit" value="Login" name="logar">
            </form>
            <p class="left"><a href="<?php echo BASE; ?>cadastro/" >Registre-se</a></p>
            <p class="rigth"><a href="#recuperar-usuario" rel="modal:open">Esqueceu a senha?</a></p>
            <div class="clear"></div>
        </div>
    </div>
</section>
