
</head>
</body>


<header>
  <div>
    <h3>SISTEMA</h3>
  </div>
</header>

<nav class="nav left">
  <div class="div-nav">
    <ul>
      <a href="<?php echo BASE; ?>" title="Home">
        <li class="active"><i class="fa fa-home" aria-hidden="true"></i></li>
      </a>
      <a href="<?php echo BASE; ?>evento" title="Criar Evento">
        <li><i class="fa fa-plus" aria-hidden="true"></i></li>
      </a>
      <a href="<?php echo BASE; ?>" title="Buscar">
        <li><i class="fa fa-search" aria-hidden="true"></i></li>
      </a>
      <a href="<?php echo BASE . 'login/sair'; ?>" title="Sair">
        <li><i class="fa fa-sign-out" aria-hidden="true"></i></li>
      </a>
    </ul>
  </div>
</nav>
<section class="map">
  <div id="map"></div>
</section>

<footer>
  <p>Amanda e Rafaela</p>
</footer>

<script
src="https://code.jquery.com/jquery-3.3.1.min.js"
integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
crossorigin="anonymous"></script>
<?php require("resultado.php"); ?>
