<!doctype html>
<html lang="pt-br">
    <head>
    <title>Eventos acadêmicos</title>
    <meta charset="utf-8">
    <meta name="viewport" content="whidth: device-width, initial-scale-1.0, maximun-scale-1.0">
    <meta name="description" content="Sistema colaborativo para divulgação de eventos científicos.">
    <meta name="keywords" content="evento, events, científico, scientific">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>reset.css">
    <link rel="stylesheet" type="text/css" href="<?php echo CSS; ?>style.css">
